services:
  backend:
    build: ./backend
    image: revisionassistant-backend
    expose:
      - "5001"
    environment:
      - SECRET_KEY=234b04d7096c179286656d3f9528ed2234628e3455a8ce1f669e0e591a0d18a3
      - OPENAI_API_KEY=sk-tC7zF1ad-KIX09x7cecqx-eGOdd_8tnSijlYMkTt2eT3BlbkFJREkc1Xe2Q2VyLCKutDZmLOpB9kbvsak1XcWULjXTMA
      - FLASK_APP=app.py
      - FLASK_ENV=production
    command: gunicorn -w 1 -b 0.0.0.0:5001 app:app
    networks:
      - custom-network

  frontend:
    build:
      context: ./webapp
      args:
        - REACT_APP_API_URL=https://questudying.com
    image: revisionassistant-frontend
    expose:
      - "3000"
    command: serve -s build -l 3000
    depends_on:
      - backend
    networks:
      - custom-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge